### PR TITLE
Implement the Request module (except DB functions)

### PR DESCRIPTION
**Pull request by micahdbak**
# Summary

Implements the Request module, and **modifies some exported functions by other modules that are used by the Request module** - will need feedback from everyone.

# Changes

Contact.kt
- Fix some warnings for value classes (make members private)
- Make `enterContactInformation` function return a possibly null value
  - The idea here is that if the person implementing this function wants to give the user the option to back out, the function can return null, instead of a Contact object
- Rename "displayContacts" to "selectContact", and have it return a Contact object or null.
  - The idea is that this function shows a listing of contacts and lets the user select one of the rows
  - The selected row is then returned as a Contact object, or null if no row was selected (go back)
  - See implementation of selectRequest for an idea of how to implement this (in this PR)

Issue.kt
- Add function definition for "saveIssue" which takes in "issueInformation"
- Rename "displayIssues" to "selectIssue" - see above comment on selectContact for info
- Make `enterIssueInformation` function return a possibly null value
  - See above comment - this is an optional functionality to whoever is implementing this function to let the user back out
- Remove "affectedRelease" from Issue class

Product.kt
- Rename "displayProducts" to "selectProduct" - see above comment on selectContact for info

Release.kt
- Rename "releaseName" to "id" in Release class
- Rename "displayReleases" to "selectRelease" - see above comment on selectContact for info

Request.kt
- Remove "anticipatedRelease" from Request class
- Add "requestDate" to Request class
- Create RequestFilter class to be used in selectRequest
- Create saveRequest function for saving a request into the DB
- Create getRequestsInDB function for getting a number of requests from the DB given a filtering mechanism
  - To be used in only Request.kt
- Implement enterRequestInformation menu
- Implement selectRequest menu
- Implement New Request menu

### CODE REVIEW

**Comment by ebarylko** [comment]
Micah, can you clarify what is the goal of the PR? When I access the requests menu from the main menu, I receive an error. Was this your intention? If so, I will approve it.

**Comment by micahdbak** [comment]
Hey! Goal of the PR is to implement the Request module, except the DB functions. So the Request module is partially complete - it's buildable, but not really interactable yet. I want to get this merged before/after the DB PR so I can work with database stuff in another PR.

**Comment by ebarylko** [comment]
Ok. I will approve. Please clarify next time in a PR whether we should expect an exception or not when testing.

> Hey! Goal of the PR is to implement the Request module, except the DB functions. So the Request module is partially complete - it's buildable, but not really interactable yet. I want to get this merged before/after the DB PR so I can work with database stuff in another PR.

**Review by ebarylko — APPROVED** [review]

**Comment by micahdbak** [comment]
> Ok. I will approve. Please clarify next time in a PR whether we should expect an exception or not when testing.

Sure will do!! Thanks

**Pull request merged**
